In [4]:
import pandas as pd

# 압축된 .gz 파일 로딩 (탭 구분)
df = pd.read_csv("target.csv")

/var/folders/4r/ccmn80ps0ms033hdrcww86kc0000gn/T/ipykernel_83898/387733225.py:4: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("target.csv")

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
## print type info

df.dtypes

cdf = df.copy()
numeric_columns = pd.to_numeric(cdf['VALUE'].str.replace(',', '', regex=True), errors='coerce')
cdf['VALUE'] = numeric_columns
cdf['VALUE'] = cdf['VALUE'].astype(float)

cdf['VALUE'].head(5)

0         23.1
1    2236000.0
2     184200.0
3     154000.0
4     951100.0
Name: VALUE, dtype: float64

In [29]:
df.sample(5)

,SOURCE_DESC,SECTOR_DESC,GROUP_DESC,COMMODITY_DESC,CLASS_DESC,PRODN_PRACTICE_DESC,UTIL_PRACTICE_DESC,STATISTICCAT_DESC,UNIT_DESC,SHORT_DESC,DOMAIN_DESC,DOMAINCAT_DESC,AGG_LEVEL_DESC,STATE_ANSI,STATE_FIPS_CODE,STATE_ALPHA,STATE_NAME,ASD_CODE,ASD_DESC,COUNTY_ANSI,COUNTY_CODE,COUNTY_NAME,REGION_DESC,ZIP_5,WATERSHED_CODE,WATERSHED_DESC,CONGR_DISTRICT_CODE,COUNTRY_CODE,COUNTRY_NAME,LOCATION_DESC,YEAR,FREQ_DESC,BEGIN_CODE,END_CODE,REFERENCE_PERIOD_DESC,WEEK_ENDING,LOAD_TIME,VALUE,CV_%
5015668,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,SILAGE,AREA HARVESTED,ACRES,"CORN, SILAGE - ACRES HARVESTED",TOTAL,NOT SPECIFIED,COUNTY,27.0,27,MN,MINNESOTA,50.0,CENTRAL,NaN,998.0,OTHER (COMBINED) COUNTIES,NaN,NaN,0.0,NaN,NaN,9000.0,UNITED STATES,"MINNESOTA, CENTRAL, OTHER (COMBINED) COUNTIES",2012,ANNUAL,0,0,YEAR,NaN,2015-06-03 15:08:31,"54,970",NaN
3275748,SURVEY,CROPS,FIELD CROPS,WHEAT,WINTER,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,AREA PLANTED,ACRES,"WHEAT, WINTER - ACRES PLANTED",TOTAL,NOT SPECIFIED,AGRICULTURAL DISTRICT,5.0,5,AR,ARKANSAS,30.0,NORTHEAST,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,9000.0,UNITED STATES,"ARKANSAS, NORTHEAST",1990,ANNUAL,0,0,YEAR,NaN,2012-01-01 00:00:00,"441,000",NaN
6365616,SURVEY,CROPS,FIELD CROPS,WHEAT,ALL CLASSES,IRRIGATED,ALL UTILIZATION PRACTICES,PRODUCTION,BU,"WHEAT, IRRIGATED - PRODUCTION, MEASURED IN BU",TOTAL,NOT SPECIFIED,COUNTY,8.0,8,CO,COLORADO,80.0,SAN LUIS VALLEY,3.0,3.0,ALAMOSA,NaN,NaN,0.0,NaN,NaN,9000.0,UNITED STATES,"COLORADO, SAN LUIS VALLEY, ALAMOSA",1970,ANNUAL,0,0,YEAR,NaN,2012-01-01 00:00:00,"19,750",NaN
6529836,SURVEY,CROPS,FIELD CROPS,SOYBEANS,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PRODUCTION,BU,"SOYBEANS - PRODUCTION, MEASURED IN BU",TOTAL,NOT SPECIFIED,COUNTY,13.0,13,GA,GEORGIA,80.0,SOUTH CENTRAL,315.0,315.0,WILCOX,NaN,NaN,0.0,NaN,NaN,9000.0,UNITED STATES,"GEORGIA, SOUTH CENTRAL, WILCOX",2007,ANNUAL,0,0,YEAR,NaN,2012-01-01 00:00:00,"23,000",NaN
2506998,SURVEY,CROPS,FIELD CROPS,WHEAT,ALL CLASSES,NON-IRRIGATED,ALL UTILIZATION PRACTICES,YIELD,BU / NET PLANTED ACRE,"WHEAT, NON-IRRIGATED - YIELD, MEASURED IN BU /...",TOTAL,NOT SPECIFIED,COUNTY,38.0,38,ND,NORTH DAKOTA,50.0,CENTRAL,43.0,43.0,KIDDER,NaN,NaN,0.0,NaN,NaN,9000.0,UNITED STATES,"NORTH DAKOTA, CENTRAL, KIDDER",1999,ANNUAL,0,0,YEAR,NaN,2012-01-01 00:00:00,18,NaN

### Weekly

In [7]:
## Weekly Frequency Data

wdf = cdf[cdf["FREQ_DESC"] == "WEEKLY"].copy().groupby(["COMMODITY_DESC", "YEAR", "LOCATION_DESC", "REFERENCE_PERIOD_DESC", "DOMAIN_DESC", "STATISTICCAT_DESC", "UNIT_DESC"]).agg({
    "VALUE": "sum",
})

wdf.sample(10, random_state=42)

                                                                                                             VALUE
COMMODITY_DESC YEAR LOCATION_DESC  REFERENCE_PERIOD_DESC DOMAIN_DESC STATISTICCAT_DESC        UNIT_DESC
WHEAT          2020 COLORADO       WEEK #28              TOTAL       PROGRESS, PREVIOUS YEAR  PCT MATURE      62.0
SOYBEANS       2016 LOUISIANA      WEEK #23              TOTAL       PROGRESS, 5 YEAR AVG     PCT EMERGED     89.0
CORN           2023 MARYLAND       WEEK #28              TOTAL       CONDITION, PREVIOUS YEAR PCT FAIR        16.0
               1988 NORTH CAROLINA WEEK #36              TOTAL       PROGRESS, 5 YEAR AVG     PCT MATURE      89.0
WHEAT          2016 CALIFORNIA     WEEK #07              TOTAL       CONDITION, PREVIOUS YEAR PCT VERY POOR    0.0
SOYBEANS       2023 MICHIGAN       WEEK #40              TOTAL       CONDITION, 5 YEAR AVG    PCT VERY POOR    1.0
WHEAT          2015 COLORADO       WEEK #24              TOTAL       PROGRESS                 PCT HARVESTED    0.0
               1993 ARKANSAS       WEEK #24              TOTAL       PROGRESS, 5 YEAR AVG     PCT HEADED     100.0
               2020 NEW JERSEY     WEEK #16              TOTAL       CONDITION, PREVIOUS YEAR PCT GOOD        50.0
CORN           2022 OHIO           WEEK #33              TOTAL       PROGRESS, PREVIOUS YEAR  PCT DENTED      35.0

In [8]:
wdf.to_csv("dataset/weekly.csv", index=True)

### Annually

In [ ]:
ydf = cdf[cdf["FREQ_DESC"] == "ANNUAL"].copy().groupby(["COMMODITY_DESC", "YEAR", "LOCATION_DESC", "DOMAIN_DESC", "STATISTICCAT_DESC", "UNIT_DESC"]).agg({
    "VALUE": "sum",
})

ydf.sample(10)

                                                                               VALUE
COMMODITY_DESC YEAR DOMAIN_DESC                   UNIT_DESC
CORN           2020 TOTAL                         REACTIONS SINCE 1984  5.920000e+02
WHEAT          1948 TOTAL                         BU / ACRE             1.081756e+05
SOYBEANS       2022 FARM SALES AND AREA HARVESTED OPERATIONS            5.417020e+05
               2020 TOTAL                         $ / BU                3.383800e+02
               2022 FARM SALES                    OPERATIONS            1.129462e+06
WHEAT          1964 TOTAL                         BU                    1.539458e+10
               1971 TOTAL                         BU                    2.523301e+10
               2007 TOTAL                         ACRES                 2.152320e+09
SOYBEANS       2017 AREA HARVESTED                ACRES                 2.764513e+08
CORN           1901 TOTAL                         ACRES                 1.888440e+08

In [ ]:
ydf.to_csv("dataset/annualy.csv", index=True)